config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tweets#index'
  resources :tags
  resources :tweets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to  :tag
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tweets = Tweet.where(tag_id: params[:id])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

    def index
      @tweets = Tweet.all
    end
  
    def new
      @tweet = Tweet.new
    end
  
    def create
      Tweet.create(tweet_params)
      # @tweet = tweet.create(tweet_params)
    end
  
    def show
      @tweet = Tweet.find(params[:id])
    end
  
    def destroy
      tweet = Tweet.find(params[:id])
      tweet.destroy
    end
  
    def edit
      @tweet = Tweet.find(tweet_params[:id])
    end
  
    def update
      tweet = Tweet.find(params[:id])
      tweet.update(tweet_params)
    end
  
    private
    def tweet_params
      params.require(:tweet).permit(:name, :text, :image, :tag_id)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title まんが
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    :javascript
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();

  %body.body
    %header.header
      .header__bar.row
        %h1.grid-6
          %a{:href => "/"} My Best まんが
        - if user_signed_in?
          .user_nav.grid-6
          %span
            = current_user.nickname
            %ul.user__info
            %li
            = link_to "マイページ", "/users/#{current_user.id}"
            = link_to "ログアウト", destroy_user_session_path, method: :delete
            = link_to  "投稿する", "tweets/new", class: "post"
        - else
          .grid-6
            = link_to "ログイン", new_user_session_path, class: 'post'
            = link_to "新規登録", new_user_registration_path, class: 'post'
            = yield

app/views/tags/new.html.haml
.category
  -@tweets.each do |tweet|
    %img{height: "600", width: "450", src: tweet.image}
    .category_1
      = link_to '詳細', "/tweets/#{tweet.id}", method: :get
        - if user_signed_in? && current_user.id == tweet.user_id
      .category_2
        =tweet.name
        .category_3
          =tweet.text
       

app/views/tweets/create.html.haml
.contents
  .contents_1
    %h3
      投稿が完了しました。
    %a.btn{:href => "/tweets"} 投稿一覧へ戻る

app/views/tweets/destroy.html.haml
.contents
  .contents_1
    %h3
      削除が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/tweets/edit.html.haml
.form
  = form_for @tweet do |f|
  %h3
    編集する
    = f.text_field :name, placeholder: "漫画のタイトル"
    = f.text_field :text, placeholder: "おすすめ箇所", rows: "10"
    = f.file_field :image, placeholder: "画像"
    = f.select :tag_id, [["アクション", 1], ["SF", 2],["スポーツ", 3],["ヤンキー・任侠", 4],["ギャンブル", 5],["ギャグ・コメディー", 6],["日常系", 7],["ヒューマンドラマ", 8],["職業・ビジネス", 9],["恋愛", 10],["歴史・時代劇", 11],["グルメ", 12],["その他", 13]]
    = f.submit "送信"

app/views/tweets/index.html.haml
.top
  %a.post{:href => "/tweets/new"} 投稿する
  .top_1
    = link_to "アクション・アドベンチャー", tag_path(1)
    = link_to "SF・ファンタジー", tag_path(2)
    = link_to "スポーツ",tag_path(3)
    .top__1
      = link_to image_tag(src= "kakutou.jpg", class: "kakutou", size: "350x400"), tag_path(1)
      = link_to image_tag(src= "fan.jpg", class: "kakutou", size: "350x400"), tag_path(2)
      = link_to image_tag(src= "supo-tu.jpg", class: "kakutou", size: "350x400"), tag_path(3)
  .top_2
    = link_to "ヤンキー・任侠", tag_path(4)
    = link_to "ギャンブル", tag_path(5)
    = link_to "ギャグ・コメディー", tag_path(6)
    .top__2
      = link_to image_tag(src= "yannki-.jpg", class: "kakutou", size: "350x400"), tag_path(4)
      = link_to image_tag(src= "gyannburu.jpg", class: "kakutou", size: "350x400"), tag_path(5)
      = link_to image_tag(src= "gyagu.jpg", class: "kakutou", size: "350x400"), tag_path(6)
  .top_3
    = link_to "日常系", tag_path(7)
    = link_to "ヒューマンドラマ", tag_path(8)
    = link_to "職業・ビジネス", tag_path(9)
    .top__3
      = link_to image_tag(src= "nitizyou.jpg", class: "kakutou", size: "350x400"), tag_path(7)
      = link_to image_tag(src= "kagaku.jpg", class: "kakutou", size: "350x400"), tag_path(8)
      = link_to image_tag(src= "bizinesu.jpg", class: "kakutou", size: "350x400"), tag_path(9)
  .top_4
    = link_to "恋愛", tag_path(10)
    = link_to "歴史・時代劇", tag_path(11)
    = link_to "グルメ", tag_path(12)
    .top__4
      = link_to image_tag(src= "rennai.jpg", class: "kakutou", size: "350x400"), tag_path(10)
      = link_to image_tag(src= "zidai.jpg", class: "kakutou", size: "350x400"), tag_path(11)
      = link_to image_tag(src= "gurume.jpg", class: "kakutou", size: "350x400"), tag_path(12)
    .top_5
    = link_to "その他", tag_path(13)
    .top__5
      = link_to image_tag(src= "sonota.jpg", class: "kakutou", size: "350x400"), tag_path(13)

app/views/tweets/new.html.haml
.form
  = form_for @tweet do |f|
    = f.text_field :name, placeholder: "漫画のタイトル"
    = f.text_field :text, placeholder: "おすすめ箇所"
    = f.file_field :image, placeholder: "画像"
    = f.select :tag_id, [["アクション・アドベンチャー", 1], ["SF・ファンタジー", 2],["スポーツ", 3],["ヤンキー・任侠", 4],["ギャンブル", 5],["ギャグ・コメディー", 6],["日常系", 7],["ヒューマンドラマ", 8],["職業・ビジネス", 9],["恋愛", 10],["歴史・時代劇", 11],["グルメ", 12],["その他", 13]]
    = f.submit "送信"
    

app/views/tweets/show.html.haml
.con
  %img{height: "600", width: "450", src: @tweet.image}
    .con_1
      - if user_signed_in? && current_user.id == tweet.user_id
      = link_to '編集', "/tweets/#{params[:id]}/edit", method: :get
      = link_to '削除', "/tweets/#{@tweet.id}", method: :delete, data: { confirm: '削除しますか?' }
      .con_2
        = @tweet.name
        .con_3
          = simple_format(@tweet.text)
          

app/views/tweets/update.html.haml
.contents
  .contents_1
    %h3
      更新が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る